# Generated by Django 3.2.4 on 2021-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('photoUrl', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=80)),
            ],
        ),
    ]
