# Generated by Django 3.2.4 on 2021-06-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('photoUrl', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1Id', to='messenger_backend.app_user')),
                ('user2Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2Id', to='messenger_backend.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('senderId', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('conversationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationId', to='messenger_backend.conversations')),
            ],
        ),
    ]
