# Generated by Django 3.2.4 on 2021-06-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='online',
            field=models.BooleanField(default=0),
        ),
    ]
