# Generated by Django 3.2.4 on 2021-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_conversations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('sender_id', models.IntegerField()),
                ('conversation_id', models.ImageField(upload_to='')),
            ],
        ),
    ]
