# Generated by Django 3.2.4 on 2021-06-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0004_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='user1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_id', to='messenger_backend.app_user'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_id', to='messenger_backend.app_user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_id', to='messenger_backend.conversations'),
        ),
    ]
