# Generated by Django 3.2.4 on 2021-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0005_auto_20210614_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='conversations',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
