# Generated by Django 3.2.4 on 2021-06-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0007_auto_20210615_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='is_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
